dist: xenial
language: python

python:
 - "2.7"
 - "3.5"
 - "3.6"
 - "3.7"

install:
  - pip install -r .requirements_dev.txt
  - pip install .

script: pytest -v --doctest-modules --cov-report=xml --cov=fast_curator tests/

after_success:
  - coverage combine
  - codecov

jobs:
  include:
    - stage: test
      script: flake8 --max-line-length=120 fast_curator tests
      name: flake8

deploy:
  provider: pypi
  user: fast-hep
  distributions: "sdist bdist_wheel"
  password:
    secure: "FJ5pfw/RUhVfRB3KgeovLMrGMtsKsBcyqwVwNlY0TVhlnG+mBYHgaLcGHeyrrtd9AHTIYVCh0tXFQULuNdVVmyNTfjsQHaq3mkmMYXPy/LhLBO6sEUGo47uFP2ZleDcF+VHdaUnFmr6G6xcsuvGoDy/TNaM5b6Yz2B/6taIXjEIyTRg0KBBZIRS5rv0QRRqZeDQYyEXx4w/XiiKUJSvE+rN4Zs0Iz5cPNu2LcCDK9PcMdi0PLfNVrsZ6UmdYAyJC4k1vOmy0HXpiTaP11WoAK3GmT04chT2t+Y1kNWqWiAlfZKm2UOuciCL+bvD7Gb99NLrPaKCvgQDilUpC3Xliu9Oi6a7s6b0EtiHVUosQOkvx1zlFCHM5NO3Jj6nKKwrlRC9mGZDyuzPIB7B9pCNMFUtTYHu5JFsxhMJNkm4VaGuH01X1vyXNJY3Co3UYf04RPGIu1AAQYJQWXhjwCP2QRWRCTPlw3myec+mYkhWhCYHVEmwfe/Cmf/9BHAlhOBqbQP5s/cgxHvv/R9BrP+HbCBcdoZ4Jx2d10HqWBuhC+vNQ8qQyWaAemgVaUslLUnboijZKLKcbXzLYMsZiydJ8GtRj4g7qL0RW9EwcZlcR7/TBGS+kigULKRh0lYWoHNKz/wZGHig7JKf3UwtA6r3Uid1FHKMSYJBeZgX68RLbd1g="
  on:
    tags: true
    repo: FAST-HEP/fast-curator
    condition: "$TRAVIS_PYTHON_VERSION == 3.6 && $TRAVIS_TAG =~ ^v[0-9]+[.][0-9]+[.][0-9]+(-rc[0-9]+|[.]dev[0-9]+)?$"
