dist: xenial
language: python

python:
 - "2.7"
 - "3.5"
 - "3.6"
 - "3.7"

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" =~ 3.[678]* ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
      source "$HOME/miniconda/etc/profile.d/conda.sh";
      hash -r;
      conda config --set always_yes yes --set changeps1 no;
      conda update -q conda;
      conda info -a;

      conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION xrootd;
      conda activate test-environment;
    fi
  - pip install -r .requirements_dev.txt
  - pip install .


script: pytest -v --doctest-modules --cov-report=xml --cov=fast_curator tests/

after_success:
  - coverage combine
  - codecov

jobs:
  include:
    - stage: test
      script: flake8 --max-line-length=120 fast_curator tests
      name: flake8

deploy:
  provider: pypi
  user: fast-hep
  distributions: "sdist bdist_wheel"
  password:
    secure: "ah5SamGw9vEqVCidbr6jW8X/Pyg6jxjOAOndJFpS8WXDta3rfUEuqx9a8cgHBvAF2bru/PCuj5hrfEJvp6b34ofhRgKNM3tT0kYsxdqm7mK91TnPvp8oaJ4kYvi6gmKB1N+XTFh2HduvJAJYiuCgSwEfcfMP9amXfoWg7FXqATraLgtqrPsSQBP2OODAFBBIglW/mo9EiWFOvG2o7YBjtQ8CaW1XI0PliGgLJTq5HheIkDo+f0yP+DGgXhsUTbOlN9SK8MgQcUmTPy59M5tLUpbL2SxKpqoh6Oh/hFy8COybIi/iDI/LRyB4Kq5/mU1lGOrQFS01uiHNu/U2C72//xKDMa5fgQQM5FNDrACmTFrxRavdRkM5usFoQWGMsIIpKyjz/7HO3ihkxZNrCn6P0C60OlU5loG6a7/gkdz40xeNjyB1B0T/j9G5OyCDN6X/T3snXseARISpez4beLY13G5i6YKDi3BpVXjlk0ttvkvqZWMQQnaKU6GE9JND3O6PqRPz64zi/HmJtI9KEuWkkBG9IeCwaA5+Ej7ApCVUmTWGPcLoRxmPBfYB/raCaVI90SsQf+hQ8Izkqr6DfAdMds0TpsXUSG9S3qiX1ECol95zrB2U2C2hVaor8bo2QkZ0IpUqVeYSEuvNx4WlvmSFX4jEkGZCBJgJULjs6Xy2dHU="
  on:
    tags: true
    repo: FAST-HEP/fast-curator
    condition: "$TRAVIS_PYTHON_VERSION == 3.6 && $TRAVIS_TAG =~ ^v[0-9]+[.][0-9]+[.][0-9]+(-rc[0-9]+|[.]dev[0-9]+)?$"
